# Generated by Django 4.2.27 on 2026-02-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('created', '주문 생성'), ('paid', '요금 지불'), ('canceled', '주문 취소'), ('expired', '기한 만료')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scode', models.CharField(help_text='1H, 7D....', max_length=20)),
                ('name', models.CharField(help_text='상품명', max_length=100)),
                ('product_type', models.CharField(choices=[('time', '사간제'), ('flat', '기간제'), ('fixed', '지정석'), ('locker', '사물함')], help_text='상품 타입', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='시간제 전용', null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='기간제 전용', null=True)),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('refunded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_admin', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_type', 'scode'), name='unique_product_type_scode'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product_type', 'time'), ('duration_minutes__isnull', False), ('duration_days__isnull', True)), models.Q(('product_type__in', ['flat', 'fixed', 'locker']), ('duration_minutes__isnull', True), ('duration_days__isnull', False)), _connector='OR'), name='chk_product_duration_shape'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payments.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_selected', to='cafe.locker'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_selected', to='cafe.seat'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
