# Generated by Django 4.2.27 on 2026-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ready', '결제 준비'), ('paid', '지불 완료'), ('canceled', '결제 취소'), ('refunded', '환불')], default='ready', max_length=10),
        ),
    ]
