# Generated by Django 4.2.27 on 2026-02-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_locker_available_alter_seat_available'),
        ('payments', '0002_payment_method_payment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='chk_product_duration_shape',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='duration_minutes',
            new_name='duration_hours',
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_selected_locker', to='cafe.locker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_selected_seat', to='cafe.seat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('time', '시간제'), ('flat', '기간제'), ('fixed', '지정석'), ('locker', '사물함')], help_text='상품 타입', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product_type', 'time'), ('duration_hours__isnull', False), ('duration_days__isnull', True)), models.Q(('product_type__in', ['flat', 'fixed', 'locker']), ('duration_hours__isnull', True), ('duration_days__isnull', False)), _connector='OR'), name='chk_product_duration_shape'),
        ),
    ]
