# Generated by Django 4.2.27 on 2026-04-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_remove_pass_order_pass_idx_pass_user_status_created_and_more'),
        ('payments', '0003_remove_product_chk_product_duration_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pass_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cafe.pass'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'created_at'], name='idx_order_user_status_created'),
        ),
    ]
