# Generated by Django 4.2.27 on 2026-04-24 09:05

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_order_pass_obj_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=payments.models.generate_order_no, editable=False, max_length=40, unique=True),
        ),
    ]
