# Generated by Django 4.2.27 on 2026-02-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='문제의 종류', max_length=20)),
                ('action', models.CharField(help_text='조치 사항', max_length=20)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
