# Generated by Django 4.2.27 on 2026-03-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='log',
            name='target_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='actor_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='entity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='entity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='logs_entity__cbd349_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['action', 'created_at'], name='logs_action_4f7812_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['actor_user_id', 'created_at'], name='logs_actor_u_a00deb_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['target_user_id', 'created_at'], name='logs_target__878715_idx'),
        ),
        migrations.AlterModelTable(
            name='log',
            table='logs',
        ),
    ]
