# Generated by Django 4.2.27 on 2026-04-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_options_log_message_log_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='actor_user_id',
            new_name='actor_user',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='target_user_id',
            new_name='target_user',
        ),
        migrations.RenameIndex(
            model_name='log',
            new_name='logs_actor_u_b6187d_idx',
            old_name='logs_actor_u_a00deb_idx',
        ),
        migrations.RenameIndex(
            model_name='log',
            new_name='logs_target__9a91c7_idx',
            old_name='logs_target__878715_idx',
        ),
    ]
