# Generated by Django 4.2.27 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_actor_user_id_log_actor_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='logs_actor_u_b6187d_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='logs_target__9a91c7_idx',
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['actor_user', 'created_at'], name='logs_actor_u_b6187d_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['target_user', 'created_at'], name='logs_target__9a91c7_idx'),
        ),
    ]
