# Generated by Django 4.2.27 on 2026-02-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('locker_no', models.CharField(max_length=20, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LockerUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assign_at', models.DateTimeField()),
                ('unassign_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('used', '사용중인'), ('unused', '미사용된')], default='unused', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pass_kind', models.CharField(choices=[('time', '시간제'), ('flat', '기간제'), ('fixed', '지정석'), ('locker', '사물함')], max_length=10)),
                ('status', models.CharField(choices=[('active', '사용 가능한'), ('expired', '만료된'), ('canceled', '취소된')], default='active', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, help_text='결제 후 생성', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='기간제 상품 끝나는 시점', null=True)),
                ('remaining_minutes', models.PositiveIntegerField(blank=True, help_text='시간제 상품 남은 시간 분으로 관리', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_no', models.CharField(max_length=20, unique=True)),
                ('seat_type', models.CharField(choices=[('normal', '일반석'), ('fixed', '지정석')], max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_at', models.DateTimeField()),
                ('expected_end_at', models.DateTimeField(help_text='자동 퇴실 시간')),
                ('check_out_at', models.DateTimeField(blank=True, help_text='수동 퇴실 시간', null=True)),
                ('status', models.CharField(choices=[('used', '사용중인'), ('unused', '미사용된')], default='unused', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pass_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_usage', to='cafe.pass')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usages', to='cafe.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='fixed_seat',
            field=models.ForeignKey(blank=True, help_text='사용자가 지정한 지정석 번호', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_passes', to='cafe.seat'),
        ),
        migrations.AddField(
            model_name='pass',
            name='locker',
            field=models.ForeignKey(blank=True, help_text='사용자가 지정한 사물함 번호', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locker_passes', to='cafe.locker'),
        ),
    ]
