# Generated by Django 4.2.27 on 2026-02-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('cafe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pass_obj', to='payments.order'),
        ),
        migrations.AddField(
            model_name='pass',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='payments.product'),
        ),
        migrations.AddField(
            model_name='pass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockerusage',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='cafe.locker'),
        ),
        migrations.AddField(
            model_name='lockerusage',
            name='pass_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locker_usages', to='cafe.pass'),
        ),
        migrations.AddField(
            model_name='lockerusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locker_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='seatusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'used')), fields=('seat',), name='uniq_used_seat_usage_per_seat'),
        ),
        migrations.AddConstraint(
            model_name='seatusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'used')), fields=('user',), name='uniq_used_seat_usage_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pass',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pass_kind', 'fixed'), ('fixed_seat__isnull', False), ('locker__isnull', True)), models.Q(('pass_kind', 'locker'), ('locker__isnull', False), ('fixed_seat__isnull', True)), models.Q(('pass_kind__in', ['time', 'flat']), ('fixed_seat__isnull', True), ('locker__isnull', True)), _connector='OR'), name='chk_pass_resource_shape'),
        ),
        migrations.AddConstraint(
            model_name='pass',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('fixed_seat',), name='uniq_active_fixed_seat_pass'),
        ),
        migrations.AddConstraint(
            model_name='pass',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('locker',), name='uniq_active_locker_pass'),
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'USED')), fields=('locker',), name='uniq_used_locker_usage_per_locker'),
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'USED')), fields=('user',), name='uniq_used_locker_usage_per_user'),
        ),
    ]
