# Generated by Django 4.2.27 on 2026-02-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lockerusage',
            name='uniq_used_locker_usage_per_locker',
        ),
        migrations.RemoveConstraint(
            model_name='lockerusage',
            name='uniq_used_locker_usage_per_user',
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'used')), fields=('locker',), name='uniq_used_locker_usage_per_locker'),
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'used')), fields=('user',), name='uniq_used_locker_usage_per_user'),
        ),
    ]
