# Generated by Django 4.2.27 on 2026-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_lockerusage_uniq_used_locker_usage_per_locker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
