# Generated by Django 4.2.27 on 2026-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_locker_available_alter_seat_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatusage',
            name='check_out_at',
        ),
    ]
