# Generated by Django 4.2.27 on 2026-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_remove_seatusage_check_out_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lockerusage',
            name='uniq_used_locker_usage_per_locker',
        ),
        migrations.RemoveConstraint(
            model_name='lockerusage',
            name='uniq_used_locker_usage_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='seatusage',
            name='uniq_used_seat_usage_per_seat',
        ),
        migrations.RemoveConstraint(
            model_name='seatusage',
            name='uniq_used_seat_usage_per_user',
        ),
        migrations.RemoveField(
            model_name='lockerusage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seatusage',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(fields=('locker',), name='uniq_active_locker_usage_per_locker'),
        ),
        migrations.AddConstraint(
            model_name='lockerusage',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_active_locker_usage_per_user'),
        ),
        migrations.AddConstraint(
            model_name='seatusage',
            constraint=models.UniqueConstraint(fields=('seat',), name='uniq_active_seat_usage_per_seat'),
        ),
        migrations.AddConstraint(
            model_name='seatusage',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_active_seat_usage_per_user'),
        ),
    ]
