# Generated by Django 4.2.27 on 2026-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_remove_lockerusage_uniq_used_locker_usage_per_locker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='order',
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['user', 'status', 'created_at'], name='idx_pass_user_status_created'),
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['user', 'pass_kind', 'status'], name='idx_pass_user_kind_status'),
        ),
    ]
