# Generated by Django 4.2.27 on 2026-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_remove_pass_order_pass_idx_pass_user_status_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='available2',
            field=models.BooleanField(default=True),
        ),
    ]
