# Generated by Django 4.2.27 on 2026-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_seat_available2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='available2',
        ),
    ]
