# Generated by Django 4.2.27 on 2026-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_remove_seat_available2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
