# Generated by Django 4.2.27 on 2026-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_seat_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='disabled',
        ),
    ]
