# Generated by Django 4.2.27 on 2026-05-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_remove_seat_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='is_active',
            new_name='is_active',
        ),
    ]
